version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/zettelkasten
permissions:
   - object: /
     pattern: "**"
     owner: ec2-user
     group: ec2-user
hooks:
  BeforeInstall:
  
  AfterInstall:
    
  ApplicationStart:
    - location: scripts/gitclone.sh
      runas: ec2-user
  ApplicationStop:
