version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/zettelkasten
permissions:
   - object: /home/ec2-user/zettelkasten
     pattern: "**"
     owner: ec2-user
     group: ec2-user
hooks:
  BeforeInstall:
#    - location: scripts/gitclone.sh
 #     runas: ec2-user
  AfterInstall:
    
  ValidateService:
    - location: scripts/gitclone.sh
      runas: ec2-user
